name: Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pip install pytest
          pytest
      - name: Build package
        run: |
            python -m pip install --upgrade build
            python -m build

      - name: Check dist directory
        run: ls -la dist
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
            user: __token__
            password: ${{ secrets.PYPI_API_TOKEN }}
            repository_url: https://upload.pypi.org/legacy/
        env:
          pythonLocation: /opt/hostedtoolcache/Python/3.12.4/x64
          PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.12.4/x64/lib/pkgconfig
          Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.4/x64
          Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.4/x64
          Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.4/x64
          LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.12.4/x64/lib
